- name: VPC | Creating VPC 
  hosts: local
  connection: local
  gather_facts: no
  vars:
    application: "virtuoso"
  vars_files:
    - aws/vars/common/profile.yml
    - aws/vars/common/credentials.yml
    - aws/vars/infra/vpc.yml
  environment:
    AWS_PROFILE: "{{ AWS_PROFILE }}"
    AWS_ACCESS_KEY_ID: "{{ AWS_ACCESS_KEY_ID }}"
    AWS_SECRET_ACCESS_KEY: "{{ AWS_SECRET_ACCESS_KEY }}"
    AWS_REGION: "{{ AWS_REGION }}"
  tasks:
    - include_tasks: aws/tasks/vpc-subnet.yml
    - include_tasks: aws/tasks/vpc-route-table.yml
    - name: VPC | Creating VPC 
      vars:
        msg: |
          . @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@                                   .
          . @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@                                   .
          .                                                                                .
          . Task done!                                                                     .
          . Your new VPC infrastructure is ready to use.                                   .
          .                                                                                .
          . @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@                                   .
          . @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@                                   .
      debug: msg="{{ msg.split('\n') }}"
