---
- name: KEY PAIR | Configuring key
  hosts: local
  connection: local
  gather_facts: no
  vars:
    application: "virtuoso"
  vars_files:
    - aws/vars/common/profile.yml
    - aws/vars/common/credentials.yml
  environment:
    AWS_PROFILE: "{{ AWS_PROFILE }}"
    AWS_ACCESS_KEY_ID: "{{ AWS_ACCESS_KEY_ID }}"
    AWS_SECRET_ACCESS_KEY: "{{ AWS_SECRET_ACCESS_KEY }}"
    AWS_REGION: "{{ AWS_REGION }}"
  tasks:
    - include_tasks: aws/tasks/set-sshkey-chmod.yml
    - include_tasks: aws/tasks/ec2-keypair.yml
    - name: KEY PAIR | Configuring key
      vars:
        msg: |
          . @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@                                   .
          . @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@                                   .
          .                                                                                .
          . Task done!                                                                     .
          . Your key was created.                                                          .
          .                                                                                .
          . @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@                                   .
          . @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@                                   .
      debug: msg="{{ msg.split('\n') }}"
