---
- name: BASTION | Creating Bastion instances
  hosts: local
  connection: local
  gather_facts: no
  vars:
    application: "virtuoso"
    service: "bastion"
  vars_files:
    - aws/vars/common/profile.yml
    - aws/vars/common/credentials.yml
    - aws/vars/infra/ec2-key.yml
    - aws/vars/infra/vpc.yml
    - aws/vars/infra/{{ service }}.yml
  environment:
    AWS_PROFILE: "{{ AWS_PROFILE }}"
    AWS_ACCESS_KEY_ID: "{{ AWS_ACCESS_KEY_ID }}"
    AWS_SECRET_ACCESS_KEY: "{{ AWS_SECRET_ACCESS_KEY }}"
    AWS_REGION: "{{ AWS_REGION }}"
  tasks:
    - include_tasks: aws/tasks/set-sshkey-chmod.yml
    - include_tasks: aws/tasks/vpc-facts.yml
    - include_tasks: aws/tasks/ec2-sg.yml
    - include_tasks: aws/tasks/ec2-instance.yml
    - name: BASTION | Creating Bastion instances
      vars:
        msg: |
          . @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@                                   .
          . @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@                                   .
          .                                                                                .
          . Task done!                                                                     .
          . Now you can connect to your bastion instance using the command below:          .
          . $ AWS_PROFILE=<profile_name> ssh -F ssh.cfg bastion                            .
          .                                                                                .
          . @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@                                   .
          . @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@                                   .
      debug: msg="{{ msg.split('\n') }}"
