---
- name: CI | Creating Jenkins instance
  hosts: local
  connection: local
  gather_facts: no
  vars:
    application: "virtuoso"
    service: "ci"
  vars_files:
    - aws/vars/common/profile.yml
    - aws/vars/common/credentials.yml
    - aws/vars/infra/vpc.yml
    - aws/vars/infra/ec2-key.yml
    - aws/vars/infra/{{ service }}.yml
  environment:
    AWS_PROFILE: "{{ AWS_PROFILE }}"
    AWS_ACCESS_KEY_ID: "{{ AWS_ACCESS_KEY_ID }}"
    AWS_SECRET_ACCESS_KEY: "{{ AWS_SECRET_ACCESS_KEY }}"
    AWS_REGION: "{{ AWS_REGION }}"
  tasks:
    - include_tasks: aws/tasks/set-sshkey-chmod.yml
    - include_tasks: aws/tasks/vpc-facts.yml
    - include_tasks: aws/tasks/set-sshkey-chmod.yml
    - include_tasks: aws/tasks/ec2-keypair.yml
    - include_tasks: aws/tasks/ec2-sg.yml
    - include_tasks: aws/tasks/ec2-instance.yml
    - include_tasks: aws/tasks/ec2-instance-warmup.yml

- name: CI | Instance software setup 1/4
  hosts: "{{ host_group_name }}"
  become: true
  remote_user: ubuntu
  vars:
    ENV: "{{ AWS_PROFILE }}"
    application: "pointr"
    service: "ci"
  vars_files:
    - aws/vars/common/profile.yml
    - aws/vars/common/credentials.yml
    - aws/vars/infra/{{ service }}.yml
  environment:
    AWS_PROFILE: "{{ AWS_PROFILE }}"
    AWS_ACCESS_KEY_ID: "{{ AWS_ACCESS_KEY_ID }}"
    AWS_SECRET_ACCESS_KEY: "{{ AWS_SECRET_ACCESS_KEY }}"
    AWS_REGION: "{{ AWS_REGION }}"
  roles:
    - roles/geerlingguy.swap
    - roles/william-yeh.oracle_java
    - roles/geerlingguy.docker
    - roles/geerlingguy.git
    - roles/geerlingguy.pip
    - roles/geerlingguy.nginx
    - roles/geerlingguy.jenkins
    - roles/virtuoso.ansible
    - roles/virtuoso.nginx-conf
    - roles/virtuoso.aws-conf

- name: CI | Instance software setup 2/4
  hosts: "{{ host_group_name }}"
  become: true
  vars:
    ENV: "{{ AWS_PROFILE }}"
    application: "pointr"
    service: "ci"
  vars_files:
    - aws/vars/common/profile.yml
    - aws/vars/common/credentials.yml
    - aws/vars/infra/{{ service }}.yml
  environment:
    AWS_PROFILE: "{{ AWS_PROFILE }}"
    AWS_ACCESS_KEY_ID: "{{ AWS_ACCESS_KEY_ID }}"
    AWS_SECRET_ACCESS_KEY: "{{ AWS_SECRET_ACCESS_KEY }}"
    AWS_REGION: "{{ AWS_REGION }}"
  roles:
    - roles/virtuoso.common-conf

- name: CI | Instance software setup 3/4
  hosts: local
  connection: local
  gather_facts: no
  vars:
    application: "virtuoso"
    service: "ci"
  vars_files:
    - aws/vars/common/profile.yml
    - aws/vars/common/credentials.yml
  environment:
    AWS_PROFILE: "{{ AWS_PROFILE }}"
    AWS_ACCESS_KEY_ID: "{{ AWS_ACCESS_KEY_ID }}"
    AWS_SECRET_ACCESS_KEY: "{{ AWS_SECRET_ACCESS_KEY }}"
    AWS_REGION: "{{ AWS_REGION }}"
  tasks:
    - name: EC2 | Getting instance facts
      ec2_instance_facts:
        filters:
          instance-state-name: running
          "tag:Name": "{{ application }}-{{ service }}"
      register: ec2_instance_fact
    - name: Stop the ec2 instance
      local_action:
        module: ec2
        instance_ids:
          - '{{ ec2_instance_fact.instances[0].instance_id }}'
        state: stopped
        wait: True
    - name: Start the ec2 instance
      local_action:
        module: ec2
        instance_ids:
          - '{{ ec2_instance_fact.instances[0].instance_id }}'
        state: running
        wait: True
    - name: Wait for SSH to come up on instance
      wait_for:
        host: "{{ ec2_instance_fact.instances[0].private_ip_address }}"
        port: 22
        delay: 10
        timeout: 120
        state: started
      delegate_to: ubuntu@bastion

- name: CI | Instance software setup 4/4
  hosts: "{{ host_group_name }}"
  become: true
  remote_user: ubuntu
  vars:
    ENV: "{{ AWS_PROFILE }}"
    application: "pointr"
    service: "ci"
  vars_files:
    - aws/vars/common/profile.yml
    - aws/vars/common/credentials.yml
    - aws/vars/infra/{{ service }}.yml
  environment:
    AWS_PROFILE: "{{ AWS_PROFILE }}"
    AWS_ACCESS_KEY_ID: "{{ AWS_ACCESS_KEY_ID }}"
    AWS_SECRET_ACCESS_KEY: "{{ AWS_SECRET_ACCESS_KEY }}"
    AWS_REGION: "{{ AWS_REGION }}"
  roles:
    - roles/virtuoso.jenkins-conf

- name: CI | Finalizing process
  hosts: local
  connection: local
  gather_facts: no
  vars:
    application: "virtuoso"
    service: "ci"
  vars_files:
    - aws/vars/common/profile.yml
    - aws/vars/common/credentials.yml
    - aws/vars/infra/{{ service }}.yml
  environment:
    AWS_PROFILE: "{{ AWS_PROFILE }}"
    AWS_ACCESS_KEY_ID: "{{ AWS_ACCESS_KEY_ID }}"
    AWS_SECRET_ACCESS_KEY: "{{ AWS_SECRET_ACCESS_KEY }}"
    AWS_REGION: "{{ AWS_REGION }}"
  tasks:
    - name: EC2 | Getting instance facts
      ec2_instance_facts:
        filters:
          instance-state-name: running
          "tag:Name": "{{ application }}-{{ service }}"
      register: ec2_instance_fact
    - name: CI | Finalizing process
      vars:
        msg: |
          . @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@                                   .
          . @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@                                   .
          .                                                                                .
          . Task done!                                                                     .
          . Wait a few seconds while the instance reboot to apply some configurations.     .
          . After it, you can access your CI/CD server using the infos below               .
          .                                                                                .
          . URL........: http://{{ ec2_instance_fact.instances[0].public_ip_address }}                                                                                .
          . User.......: {{ jenkins_admin_username }}                                                                                .
          . Password...: {{ jenkins_admin_password }}                                                                                .
          .                                                                                .
          .                                                                                .
          . @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@                                   .
          . @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@                                   .
      debug: msg="{{ msg.split('\n') }}"
