---
- name: EC2 | Create Security Group
  ec2_group:
    name: "{{ item.sg_name }}"
    description: "{{ item.sg_description }}"
    region: "{{ vpc_region }}"
    vpc_id: "{{ vpc_id }}"
    state: present
    purge_rules: true
    purge_rules_egress: true
    rules: "{{ item.sg_rules }}"
    rules_egress: "{{ item.rules_egress }}"
  with_items: "{{ security_groups }}"
  register: ec2_sg

- name: EC2 | Tag the Security Group with a name
  ec2_tag:
    resource: "{{ item.group_id}}"
    region: "{{ vpc_region }}"
    state: present
    tags:
      Name: "{{ item.item.sg_name }}"
  with_items: "{{ ec2_sg.results }}"
